import { Box, Input, Stack } from "@mui/joy";
import { useEffect, useState } from "react";
import { Joystick, JoystickShape } from "react-joystick-component";
import PowerSettingsNewIcon from "@mui/icons-material/PowerSettingsNew";
import Head from "next/head";

export default function Car() {
	const [ws, setWs] = useState<WebSocket | null>(null);
	const [websocketAddress, setWebsocketAddress] = useState('192.168.1.20');
	const [joystick, setJoystick] = useState<{ x: number; y: number }>({ x: 0, y: 0 });
	const [websocketConnected, setWebsocketConnected] = useState(false);

	useEffect(() => {
		const connectWebSocket = () => {
			const newWs = new WebSocket(`ws://${websocketAddress}:81`);
			newWs.onopen = () => {
				console.log('WebSocket connected');
				setWs(newWs);
				setWebsocketConnected(true); // WebSocket is connected
				sendCoordinates();
			};
			newWs.onclose = () => {
				console.log('WebSocket closed');
				setWs(null);
				setWebsocketConnected(false); // WebSocket is disconnected
			};
		};

		connectWebSocket();
	}, [websocketAddress]);

	const sendCoordinates = () => {
		if (ws && ws.readyState === WebSocket.OPEN) {
			ws.send(`{x:${joystick.x}, y:${joystick.y}}`);
			console.log(`{x:${joystick.x}, y:${joystick.y}}`);
		}
	};

	const onMoveX = (eventAxis: any) => {
		if (eventAxis.x) {
			setJoystick((prevJoystick) => ({ ...prevJoystick, x: eventAxis.x }));
		}
	};

	const onMoveY = (eventAxis: any) => {
		if (eventAxis.y) {
			setJoystick((prevJoystick) => ({ ...prevJoystick, y: eventAxis.y }));
		}
	};

	const onStop = (pos: "x" | "y") => () => {
		setJoystick((prevJoystick) => ({
			...prevJoystick,
			...{ [pos === "x" ? "x" : "y"]: 0 },
		}));
	};

	return (
		<Box>
			<Head>
				<title>Controle | FoodCar</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Stack
				spacing={5}
				direction={"row"}
				sx={{
					justifyContent: "center",
					justifyItems: "center",
					mt: 5,
				}}
			>
				<div>
					x
					<Joystick
						size={200}
						sticky={false}
						baseColor="lightgray"
						stickColor="gray"
						move={onMoveX}
						stop={onStop('x')}
						controlPlaneShape={JoystickShape.AxisX}
					/>
				</div>
				<Stack sx={{ alignItems: "center" }} spacing={2}>
					<PowerSettingsNewIcon
						sx={{
							color: websocketConnected ? 'lightgreen' : 'yellow',
						}}
					/>
					<Input
						onChange={(e) => setWebsocketAddress(e.target.value)}
						startDecorator={"IP:"}
						sx={{
							width: 150,
							justifyContent: "center",
							alignContent: 'center',
							alignItems: 'center',
						}}
						value={websocketAddress}
					/>
				</Stack>
				<Joystick
					size={200}
					sticky={false}
					baseColor="lightgray"
					stickColor="gray"
					move={onMoveY}
					stop={onStop('y')}
					controlPlaneShape={JoystickShape.AxisY}
				/>
				y
			</Stack>
		</Box>
	);
}
